weather
YoungersBot/bot pull request #12
Opened 2023-11-12 08:48 UTC by Donvik1976

2023-11-12 17:47 UTC, TimofeiN commented on app/weather_api.py
> +        pprint(data)
принт нам нужен тут? это для отладки наверное.

2023-11-12 17:53 UTC, TimofeiN approved these changes

2023-11-12 18:44 UTC, TimofeiN requested changes

2023-11-12 18:44 UTC, TimofeiN commented on app/weather_api.py
> +        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
Это только для локальной разработки - в контейнере работать не будет

2023-11-12 18:44 UTC, TimofeiN commented on app/weather_api.py
> +from dotenv import load_dotenv
pprint, dotenv - не установлены в poetry

2023-11-15 00:51 UTC, TimofeiN approved these changes

2023-11-16 16:51 UTC, Dilbazi1 approved these changes

2023-11-16 16:52 UTC, Kent1004 approved these changes

2023-11-17 06:56 UTC, merged